# Evaluation on TOFU metrics.
# python evaluate.py --config configs/tofu_eval.yaml [--model_path=...]

model_family: qwen2.5-1.5b
model_path: outputs/unlearn/grad_ascent/forget10/tofu/qwen2.5-1.5b
quantization: none

dataset: TOFU

eval_tasks:
  - name: eval_log_forget
    data_path: data/tofu
    split: forget10
    question_key: question
    answer_key: answer
    base_answer_key: paraphrased_answer
    perturbed_answer_key: perturbed_answer

  - name: eval_log_forget_rephrase
    data_path: data/tofu
    split: forget10
    question_key: paraphrased_question
    answer_key: answer
    base_answer_key: paraphrased_answer
    perturbed_answer_key: perturbed_answer

  - name: eval_log_retain
    data_path: data/test
    split: test_retain_tofu
    question_key: question
    answer_key: answer
    base_answer_key: paraphrased_answer
    perturbed_answer_key: perturbed_answer

  - name: eval_log_retain_rephrase
    data_path: data/test
    split: test_retain_tofu
    question_key: paraphrased_question
    answer_key: answer
    base_answer_key: paraphrased_answer
    perturbed_answer_key: perturbed_answer

  - name: eval_real_author_wo_options
    data_path: data/test
    split: real_authors_perturbed
    question_key: question
    answer_key: answer
    base_answer_key: answer
    perturbed_answer_key: perturbed_answer

  - name: eval_real_world_wo_options
    data_path: data/test
    split: world_facts_perturbed
    question_key: question
    answer_key: answer
    base_answer_key: answer
    perturbed_answer_key: perturbed_answer

max_new_tokens: 128
max_length: 500
do_sample: false

batch_size: 4
gen_batch_size: 16
bf16: true
save_dir: null
